import { Inter } from "next/font/google";
import NavBar from "./ui/nav-bar"
import "./globals.css";
import 'feather-icons/dist/feather.min.js';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-gray-100`}>
        <NavBar />
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
